title: Jnana Deepthi
logo: assets/images/WhatsApp Image 2024-04-23 at 1.21.43 PM-2.jpeg
description: Undergraduate Biology Student
# show_downloads: true
linkedin: [LinkedIn](https://www.linkedin.com/in/jnana-deepthi-vishnumolakala-5a8381239/)
theme: jekyll-theme-minimal

