title: Jnana Deepthi
#logo: ![WhatsApp Image 2024-04-23 at 1 21 43 PM](https://github.com/jnanadeepthiv/portfolio/assets/167854743/d7c9e615-322e-42eb-873d-a1dc47af02e7)
description: Undergraduate Biology Student
# show_downloads: true
linkedin: [LinkedIn](https://www.linkedin.com/in/jnana-deepthi-vishnumolakala-5a8381239/)
theme: jekyll-theme-minimal

