title: Jnana Deepthi
logo: assets/images/WhatsApp Image 2024-04-23 at 1.21.43 PM-2.jpeg
description: Undergraduate Biology Student
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate Biology Student
  <br><br>
  <a href="https://www.linkedin.com/in/jnana-deepthi-vishnumolakala-5a8381239/">View My LinkedIn Profile</a> 

#show_downloads: true

theme: jekyll-theme-minimal

